export const resourceProperties = {
  APP_NAME: "Fiscalismia",
  APP_URL: 'http://localhost:5173/',
  OVERVIEW: 'Übersicht',
  HOME: 'Home',
  DEALS: 'Angebote',
  FOOD_PRICES: 'Lebensmittelpreise',
  GROCERY_DEALS: 'Supermarkt Angebote',
  GROCERIES: 'Lebensmittel',
  LOGOUT: 'Logout',
  MONTHLY_BUDGET:'Monatliches Budget',
  SAVINGS: 'Ersparnisse',
  SALES: 'Verkäufe',
  LIVING_ESSENTIALS:'Wohnen & Essentielles',
  RECREATION_RELAXATION:'Freizeit & Erholung',
  STORES: 'Verkaufsplattformen',
  INDULGENCES:'Genussmittel',
  COPYRIGHT: 'Copyright ©',
  VARIABLE_EXPENSES: 'Variable Ausgaben',
  INCOME: 'Einkommen',
  FIXED_COSTS: 'Fixkosten',
  SETTINGS: 'Einstellungen',
  GITHUB_REPO:'Github Repository',
  GITHUB_REPOS:'Github Repositories',
  FRONTEND: 'Frontend',
  BACKEND: 'Backend',
  INTERVAL_MONTHLY: 'monatlich',
  INTERVAL_QUARTERLY: 'quartalsweise',
  INTERVAL_HALFYEARLY: 'halbjährlich',
  INTERVAL_YEARLY: 'jährlich',
  FIXED_COSTS_MONHTLY_COST: 'Gesamtkosten',
  FIXED_COSTS_RENT_UTILITIES: 'Miete & Nebenkosten',
  FIXED_COSTS_DSL_PHONE: 'DSL & Mobilfunk',
  FIXED_COSTS_SPORTS_HEALTH: 'Sport & Gesundheit',
  FIXED_COSTS_MEDIA_ENTERTAINMENT: 'Medien & Unterhaltung',
  FIXED_COSTS_INSURANCE: 'Versicherungen',
  FIXED_COSTS_STUDENT_LOANS: 'Studienkredite',
  CURRENCY_EURO: '€',
  GITHUB_FRONTEND_URL: 'https://github.com/hangrybear666/fiscalismia-frontend',
  GITHUB_BACKEND_URL: 'https://github.com/hangrybear666/fiscalismia-backend',
};