export const resourceProperties = {
  APP_NAME: "Fiscalismia",
  APP_URL: 'http://localhost:5173/',
  OVERVIEW: 'Übersicht',
  HOME: 'Home',
  DEALS: 'Angebote',
  DATE: 'Datum',
  EURO: '€',
  FOOD_PRICES: 'Lebensmittelpreise',
  GROCERY_DEALS: 'Supermarkt Angebote',
  GROCERIES: 'Lebensmittel',
  LOGOUT: 'Logout',
  MONTHLY_BUDGET:'Monatliches Budget',
  SAVINGS: 'Ersparnisse',
  SALES: 'Verkäufe',
  LIVING_ESSENTIALS:'Wohnen & Essentielles',
  RECREATION_RELAXATION:'Freizeit & Erholung',
  STORES: 'Verkaufsplattformen',
  INDULGENCES:'Genussmittel',
  COPYRIGHT: 'Copyright ©',
  VARIABLE_EXPENSES: 'Variable Ausgaben',
  INCOME: 'Einkommen',
  FIXED_COSTS: 'Fixkosten',
  SETTINGS: 'Einstellungen',
  GITHUB_REPO:'Github Repository',
  GITHUB_REPOS:'Github Repositories',
  FRONTEND: 'Frontend',
  BACKEND: 'Backend',
  INTERVAL_MONTHLY: 'monatlich',
  INTERVAL_QUARTERLY: 'quartalsweise',
  INTERVAL_HALFYEARLY: 'halbjährlich',
  INTERVAL_YEARLY: 'jährlich',
  FIXED_COSTS_MONHTLY_COST: 'Gesamtkosten',
  FIXED_COSTS_RENT_UTILITIES: 'Miete & Nebenkosten',
  FIXED_COSTS_DSL_PHONE: 'DSL & Mobilfunk',
  FIXED_COSTS_SPORTS_HEALTH: 'Sport & Gesundheit',
  FIXED_COSTS_SPORTS_HEALTH_CATEGORY1: 'Studiomitgliedschaften',
  FIXED_COSTS_SPORTS_HEALTH_CATEGORY2: 'Supplemente: Gesundheit',
  FIXED_COSTS_SPORTS_HEALTH_CATEGORY3: 'Supplemente: Leistung',
  FIXED_COSTS_SPORTS_HEALTH_CATEGORY4: 'Physio & Gesundheitskurse',
  FIXED_COSTS_MEDIA_ENTERTAINMENT: 'Medien & Unterhaltung',
  FIXED_COSTS_MEDIA_ENTERTAINMENT_CATEGORY1: 'Gaming',
  FIXED_COSTS_MEDIA_ENTERTAINMENT_CATEGORY2: 'Filme & Serien',
  FIXED_COSTS_MEDIA_ENTERTAINMENT_CATEGORY3: 'Musik & Podcasts',
  FIXED_COSTS_INSURANCE: 'Versicherungen',
  FIXED_COSTS_STUDENT_LOANS: 'Studienkredite',
  CURRENCY_EURO: '€',
  GITHUB_FRONTEND_URL: 'https://github.com/hangrybear666/fiscalismia-frontend',
  GITHUB_BACKEND_URL: 'https://github.com/hangrybear666/fiscalismia-backend',
};

export const fixedCostCategories = {
  LIVING_ESSENTIALS_KEY: 'LIVING_ESSENTIALS',
  LIVING_ESSENTIALS_VALUE: 'Lebensnotwendiges',
  INTERNET_AND_PHONE_KEY: 'INTERNET_AND_PHONE',
  INTERNET_AND_PHONE_VALUE: 'Internet & Mobilfunk',
  INSURANCE_KEY: 'INSURANCE',
  INSURANCE_VALUE: 'Versicherungen',
  STUDENT_LOANS_KEY: 'STUDENT_LOANS',
  STUDENT_LOANS_VALUE: 'Studienkredite',
  LEISURE_MUSIC_PODCASTS_KEY: 'LEISURE_MUSIC_PODCASTS',
  LEISURE_MUSIC_PODCASTS_VALUE: 'Musik & Podcasts',
  LEISURE_TV_CINEMA_KEY: 'LEISURE_TV_CINEMA',
  LEISURE_TV_CINEMA_VALUE: 'Filme & Serien',
  LEISURE_GAMING_KEY: 'LEISURE_GAMING',
  LEISURE_GAMING_VALUE: 'Gaming',
  SPORTS_FACILITIES_KEY: 'SPORTS_FACILITIES',
  SPORTS_FACILITIES_VALUE: 'Studiomitgliedschaften',
  SUPPLEMENTS_HEALTH_KEY: 'SUPPLEMENTS_HEALTH',
  SUPPLEMENTS_HEALTH_VALUE: 'Supplemente: Gesundheit',
  SUPPLEMENTS_PERFORMANCE_KEY: 'SUPPLEMENTS_PERFORMANCE',
  SUPPLEMENTS_PERFORMANCE_VALUE: 'Supplemente: Leistung',
  PHYSIO_AND_HEALTH_COURSES_KEY: 'PHYSIO_AND_HEALTH_COURSES',
  PHYSIO_AND_HEALTH_COURSES_VALUE: 'Physio & Gesundheitskurse',
}