export const paths = {
  APP_ROOT_PATH: "/fiscalismia",
  LOGIN: "/login",
  VARIABLE_EXPENSES_OVERVIEW: "variable_expenses/overview",
  VARIABLE_EXPENSES_STORES: "variable_expenses/stores",
  VARIABLE_EXPENSES_INDULGENCES: "variable_expenses/indulgences",
  FIXED_COSTS_OVERVIEW: "fixed_costs/overview",
  FIXED_COSTS_LIVING_ESSENTIALS: "fixed_costs/essentials",
  FIXED_COSTS_RECREATION_RELAXATION: "fixed_costs/leisure",
  INCOME_OVERVIEW: "income/overview",
  INCOME_MONTHLY_BUDGET: "income/budget",
  INCOME_SALES: "income/sales",
  INCOME_SAVINGS: "income/savings",
  DEALS_OVERVIEW: "deals/overview",
  DEALS_FOOD_PRICES: "deals/food_prices",
  DEALS_GROCERY_DEALS: "deals/grocery_deals",
  ADMIN_UPLOAD_AREA: "admin/upload",
};