name: Fiscalismia-Frontend Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: |
        npm ci
        npm i -g snyk

    - name: Compiler Type Checks
      run: npm run typeCheck

    - name: Eslint Analysis
      run: npm run eslintAnalysis

    # - name: Snyk Static Code Security Analysis
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   run: |
    #     snyk auth $SNYK_TOKEN
    #     npm run snykCodeAnalysis

    # - name: Snyk Dependency Security Analysis
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   run: |
    #     snyk auth $SNYK_TOKEN
    #     npm run snykDependencyAnalysis

    - name: Publish Typecheck & Eslint & Snyk Reports
      uses: actions/upload-artifact@v4
      with:
        name: Fiscalismia-Frontend-Reports
        path: |
          reports/
          !reports/.gitkeep

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build --pull --rm -f "Dockerfile" -t ghcr.io/hangrybear666/fiscalismia-frontend:latest "."

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Docker Image to GHCR
      run: docker push ghcr.io/hangrybear666/fiscalismia-frontend:latest


